Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Include:
    - Gemfile
    - lib/tasks/*
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - config/initializers/*
    - config/environments/*
    - db/migrate/*
    - bin/*

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false